### ISSUE TITLE
0xkeesmark - [H-1] Call Send is a Potential Reentrancy Attack Risk

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zap-protocol-judging#119]
0xkeesmark

high

# [H-1] Call Send is a Potential Reentrancy Attack Risk

## Summary

Although the BNB token is a standard ERC20 token, when sending BNB to a user, the function uses (bool sent, ) = payable(sender).call{value: pctAmount}("");. This approach is potentially susceptible to reentrancy attacks.

## Vulnerability Detail

The code snippet below is used to send BNB tokens. While other tokens use safeTransfer, this function uses call to send the BNB token, which poses a risk of reentrancy:

```javascript
@> (bool sent, ) = payable(sender).call{value: pctAmount}("");
   require(sent, "Failed to send BNB to receiver");
```

## Impact

There is a potential risk of reentrancy when using call to send ERC20 tokens. It is recommended to use safeTransfer for ERC20 tokens or follow CEI pattern.

## Code Snippet

<https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/Vesting.sol#L84>

## Tool used

Manual Review

## Recommendation

To mitigate the risk of reentrancy attacks, use the ReentrancyGuard and follow the Checks-Effects-Interactions pattern:

```diff
+ import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

- function claim() external {
+ function claim() nonReentrant external {

+   s.index = uint128(i);
+   s.amountClaimed += pctAmount;
  if (address(token) == address(1)) {
     (bool sent, ) = payable(sender).call{value: pctAmount}("");
     require(sent, "Failed to send BNB to receiver");
   } else {
    token.safeTransfer(sender, pctAmount);
   }
-   s.index = uint128(i);
-   s.amountClaimed += pctAmount;
```

**Comment by ghost** [comment]
This can be considered as duplicate of #119

**Comment by keesmark** [comment]
@Hash01011122 
I think you are wrong issue pointed actually #157 
#119 is this issue.
