### ISSUE TITLE
ZdravkoHr. - Investors can claim back all the tax they have paid

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zap-protocol-judging#131]
ZdravkoHr.

medium

# Investors can claim back all the tax they have paid

## Summary
Because of a wrong if check in [`TokenSale.claim()`](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/c2ad35aa844899fa24f6ed0cbfcf6c7e611b061a/zap-contracts-labs/contracts/TokenSale.sol#L382-L384), investors that claim remaining USDC will get back the tax for all the tokens they have invested. They should receive the tax only for the tokens that they claim back instead.

## Vulnerability Detail
Investors are allowed to deposit up to `amount` of USDC by calling [`TokenSale.deposit()`](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/c2ad35aa844899fa24f6ed0cbfcf6c7e611b061a/zap-contracts-labs/contracts/TokenSale.sol#L162-L184). The `amount` is calculated as:
$max(maxAllocation, userTierAllc, nextTierAllocation, giftedTierAllocation)$ 

Let's say that:
 - maxAllocation = `10_000`
 - userTierAllc = `12_500`
 - nextTierAllocation = `14_700`
 - giftedTierAllocation = `11_000`

On top of that, let's assume:
 - totalSupplyInValue = `35_000`
 - totalPrivateSold = `30_000`
 - taxRate = `10%`

The user will deposit `10_000` USDC and pay a fee of `10%`, i.e `100 USDC`. Now we have:
 - totalSupplyInValue = `35_000`
 - totalPrivateSold = `40_000`

When the private phase has finished, the user can claim back `1250 USDC` (computed in [`_claim()`](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/c2ad35aa844899fa24f6ed0cbfcf6c7e611b061a/zap-contracts-labs/contracts/TokenSale.sol#L394C1-L406C6)). They should be able to claim additional `125 USDC` because that is 10% tax of the 1250 which don't count towards the deposited amount anymore.

Let's look at the code that refunds the tax. If `taxFreeAllc >= s.share`, the whole taxAmount (`500 USDC`) will be refunded. This if check is added to prevent the contract from returning to the user a tax for amount that was not paid by them because of free allocations.
For example, if the taxFreeAlocations were 1000, the share is 800 and the left is 300, the user should not get refund for all 300 tokens, but only for 100 instead. However, the implementation is wrong.

Currently, `s.share = 8750` and `taxFreeAllc = userTierAllocation = 12_500`. So the if statement will be executed and the user will receive a refund of the whole deposit - 500 USDC instead of 125 USDC. 

As a result the user has deposited 8750 USDC for free.

```solidity
        if (s.taxAmount > 0) {
            uint256 tax = userTaxRate(s.amount, msg.sender);
            uint256 taxFreeAllc = _maxTaxfreeAllocation(msg.sender) * PCT_BASE;
            if (taxFreeAllc >= s.share) {
                refundTaxAmount = s.taxAmount;
            } else {
                refundTaxAmount = (left * tax) / POINT_BASE;
            }
            usdc.safeTransferFrom(marketingWallet, msg.sender, refundTaxAmount);
        }
```

## Impact
Loss of funds for the admin wallet

#### _processPrivate()
```solidity
        require(sum <= maxAllocationOfUser, "upto max allocation");
        uint256 taxFreeAllcOfUser = 0; // hardcode zero - all pools have ax

        uint256 userTaxAmount;

        if (sum > taxFreeAllcOfUser) {
            uint256 userTxRate = userTaxRate(sum, _sender);
            if (s.amount < taxFreeAllcOfUser) {
                userTaxAmount =
                    ((sum - taxFreeAllcOfUser) * userTxRate) /
                    POINT_BASE;
            } else {
                userTaxAmount = (amount * userTxRate) / POINT_BASE;
            }
        }
```

#### _maxTaxfreeAllocation()
```solidity
    function _maxTaxfreeAllocation(address _sender) internal returns (uint256) {
        uint256 userTierAllc = stakingContract.getAllocationOf(_sender);
        uint256 giftedTierAllc = tokensaleTiers[_sender];

        if (userTierAllc > giftedTierAllc) {
            return userTierAllc;
        } else {
            return giftedTierAllc;
        }
    }
```
## Tool used

Manual Review

## Recommendation
Make the variable for tax free allocations in `deposit()` global and use it instead of `_maxTaxfreeAllocation()`

**Comment by spacegliderrrr** [comment]
Escalate

Not a valid dup. The watson has not properly pointed out the issue. They've stated
> For example, if the taxFreeAlocations were 1000, the share is 800 and the left is 300, the user should not get refund for all 300 tokens, but only for 100 instead. However, the implementation is wrong.

Tax refund should be on the whole `left` amount + the delta of `s.share - taxFreeAllcOfUser`. So in said scenario the user should get full tax refund. What the user has stated is incorrect.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Not a valid dup. The watson has not properly pointed out the issue. They've stated
> > For example, if the taxFreeAlocations were 1000, the share is 800 and the left is 300, the user should not get refund for all 300 tokens, but only for 100 instead. However, the implementation is wrong.
> 
> Tax refund should be on the whole `left` amount + the delta of `s.share - taxFreeAllcOfUser`. So in said scenario the user should get full tax refund. What the user has stated is incorrect.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ZdravkoHr** [comment]
I agree with the escalation that this is not a duplicate. However, it should not be invalidated, it's a different issue. It shows how users are able to get back more tax amount than they have to.

**Comment by ghost** [comment]
Can you please respond more about it @ZdravkoHr on why would you consider it valid?

**Comment by ZdravkoHr** [comment]
@Hash01011122 , because the user ends up with additional amount refunded

**Comment by ghost** [comment]
Responded in #159

**Comment by Evert0x** [comment]
@Hash01011122 so you are saying that this is a duplicate of #159?

**Comment by ghost** [comment]
@Evert0x Root cause of #159 and this one is same, the reason which I feel this should remain invalid is because a user is entitled to a full tax refund only if their tax-free allocation exceeds the s.share amount, which is the actual amount of funds used. This condition would render the issue invalid.

**Comment by Evert0x** [comment]
Planning to accept escalation and remove duplication status which invalidate the issue

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [spacegliderrrr](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/131/#issuecomment-2024857230): accepted
