### ISSUE TITLE
AMOW - Overwriting amount in `updateDepositBalance`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zap-protocol-judging#136]
AMOW

high

# Overwriting amount in `updateDepositBalance`

## Summary

User amount should be incremented instead of overwritten
## Vulnerability Detail

When userBalances [are updated](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/c2ad35aa844899fa24f6ed0cbfcf6c7e611b061a/zap-contracts-labs/contracts/Vesting.sol#L61-L62) in `Vesting.updateUserDeposit`, the function overwrites `_amount` instead of incrementing/decrementing. This would allow doublespending in case the user spends their entire balance just before updating.

## Impact
Loss of funds 
## Code Snippet
```solidity
    userdetails[_users[i]].userDeposit = _amount[i];
    amount += _amount[i];
```
## Tool used
Manual Review

## Recommendation
Increment/Decrement instead of directly assigning `_amount`

Duplicate of #55

**Comment by spacegliderrrr** [comment]
Escalate

(on behalf of watson) should be a dup of #55

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> (on behalf of watson) should be a dup of #55

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
Agreed this is indeed duplicate of issue #55

**Comment by Evert0x** [comment]
Planning to accept escalation, as issue was valid during creation of escalation. However it will stay invalid as the main issue will be invalid

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #55

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [spacegliderrrr](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/136/#issuecomment-2024860658): accepted
