### ISSUE TITLE
dipp - Users are able to claim more tokens than they are entitled to by calling Vesting.claim multiple times.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zap-protocol-judging#170]
dipp

high

# Users are able to claim more tokens than they are entitled to by calling Vesting.claim multiple times.

## Summary

An incorrect condition (`require(s.index != vestingPoints.length, "already claimed")`) in the `Vesting.sol` contract's `claim` function allows a user that has already fully claimed to claim multiple times and steal tokens.

## Vulnerability Detail

When a user has fully claimed, their userDetails.index is updated to be equal to `vestingPoints.length - 1`.

When they call `claim` again the `require(s.index != vestingPoints.length, "already claimed")` always passes since index cannot exceed `vestingPoints.length - 1`.

The loop will trigger for vestingPoints[1][0] only since the `i <= vestingPoints.length - 1` is always true when i=s.index=1.

The user then receives additional tokens they are not entitled to.

## Impact

Users that have fuilly claimed may call the `claim` function multiple times to claim additional tokens. Other users may be unable to claim if there are not enough tokens in the contract.

## Code Snippet

[Vesting.sol#L72](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/Vesting.sol#L72)

## Tool used

Manual Review

## Recommendation

Change `require(s.index != vestingPoints.length, "already claimed")` to `require(s.index != vestingPoints.length - 1 , "already claimed")`.

**Comment by shubham-antier** [comment]
Issue fixed: Modified the require check

**Comment by vsharma4394** [comment]
@Hash01011122  This finding is invalid becasue when a user has fully claimed, the userDetails.index is updated to be equal to vestingPoints.length .In for loop i++ increases the value of i upto vestingPoints.length and when it is reached for loop is not entered.

**Comment by Hash01011122** [comment]
I initially considered it as High but lack of communication from sponsors and Lead Senior Watson disagreeing to this one made me invalidating issue. But as sponsors have confirmed I think this should be considered as a valid High @Czar102
