### ISSUE TITLE
enfrasico - Loss of gas yield for protocol across all contracts

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zap-protocol-judging#41]
enfrasico

high

# Loss of gas yield for protocol across all contracts

## Summary
Blast has the unique implementation of sharing the sequencer fees. Any contract deployed on Blast has the ability to partake in this revenue sharing model. They are reward more, proportionate to the amount of gas the contract has spent.

## Vulnerability Detail
Zap protocol does not have any implementation that interacts with Blast precompile at `0x4300000000000000000000000000000000000002` address.

As a result, default yield mode is VOID and the protocol is unable to change it, and impossible to claim and yield from Blast.

## Impact
Loss of gas yield across all contracts.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/TokenSale.sol#L30

## Tool used

Manual Review

## Recommendation
Consider adding a wrapper around all contracts that are interacted with frequently, that allows protocol to set yield mode and claim the yield.

**Comment by Coareal** [comment]
Escalate

This is a very clear valid high. Zap protocol currently does not have any ability to partake in the revenue sharing model of Blast due to missing implementation in claiming gas yield across all contracts. 

Every contract deployed on Blast is eligible for this gas refund ONLY IF the contract is capable of interacting with the Blast precompile. 

This is a loss of fund with 100% certainty for Zap protocol, hence a high severity issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is a very clear valid high. Zap protocol currently does not have any ability to partake in the revenue sharing model of Blast due to missing implementation in claiming gas yield across all contracts. 
> 
> Every contract deployed on Blast is eligible for this gas refund ONLY IF the contract is capable of interacting with the Blast precompile. 
> 
> This is a loss of fund with 100% certainty for Zap protocol, hence a high severity issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
I am not able to make sense of what you are trying to say @Coareal, it would be great of you could describe more about the issue.

**Comment by Coareal** [comment]
Hi @Hash01011122, maybe you could point out what is confusing about this issue, so I could assist here.

The general idea in this issue is that, every transaction made on a contract on Blast, is entitled to some amount of gas fees. More gas fees are given to the protocol if more users interact with their contracts.

**Comment by ghost** [comment]
To be honest its clearly invalid because your issue doesn't show how any of the following you mentioned had any impact on protocol whatsoever.

**Comment by Coareal** [comment]
Thank you for your response, but I believe I have been very clear in my report. 

Please do refer to [Blast's docs](https://docs.blast.io/building/guides/gas-fees) for more details on Blast's gas yield.

**Comment by Evert0x** [comment]
Planning to reject escalation and keep invalid.

It's a design choice to set the yield mode

**Comment by Coareal** [comment]
Pinging protocol team @shubham-antier to clarify if this is merely a design choice, or if protocol intends to benefit from the gas yield on Blast.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Coareal](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/41/#issuecomment-2025906507): rejected
