### ISSUE TITLE
enfrasico - Native ETH in the `Vesting.sol` contract cannot accrue yield

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zap-protocol-judging#44]
enfrasico

high

# Native ETH in the `Vesting.sol` contract cannot accrue yield

## Summary
Native ETH residing in the `Vesting.sol` contract cannot accrue yield due to lacking implementations to do so. Blast is a yield-bearing chain. But the default yield mode for native ETH is VOID.  Since the contract does not configure the yield mode, yield is never accrued.

## Vulnerability Detail
The vesting contract is meant to receive ETH. This can be confirmed by the `claim()` function which sends native ETH from the contract to sender as seen in the line below.

```javascript
(bool sent, ) = payable(sender).call{value: pctAmount}(""); 
```

Since there are native ETH residing in the contract, protocol is losing out on the yield meant to be accrued on Blast, and there is no way to activate it.

## Impact
Loss of yield in vesting contract.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/Vesting.sol#L84

## Tool used

Manual Review

## Recommendation
Add a wrapper around the vesting contract which allows interoperability with Blast chain.

**Comment by Coareal** [comment]
Escalate

This is a clear valid issue. I believe this to be a high severity issue as it is a loss of yield/fund with 100% certainty. The vesting contract is meant to hold ETH, and any ETH residing in the contract cannot accrue yield due to the inability to do so. This is a loss of funds for protocol. 

Please do refer to the documentation for more context of Blast's native yield https://docs.blast.io/building/guides/eth-yield

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is a clear valid issue. I believe this to be a high severity issue as it is a loss of yield/fund with 100% certainty. The vesting contract is meant to hold ETH, and any ETH residing in the contract cannot accrue yield due to the inability to do so. This is a loss of funds for protocol. 
> 
> Please do refer to the documentation for more context of Blast's native yield https://docs.blast.io/building/guides/eth-yield

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
Did consider this issue valid medium then had second thoughts on whether protocol's priority is to accrue yield or not. It would be better if sponsors can confirm about this.

**Comment by Coareal** [comment]
I'm not sure what you mean by whether protocol's priority is to accrue yield. Blast is a yield bearing L2. Holding ETH on Blast is inherently more risky than holding it on other L2. Any protocol that is going to be deployed on it should be expected to handle yield collection correctly. This issue is a definitive loss of fund.

According to Sherlock's criteria for High severity,

> Definite loss of funds without (extensive) limitations of external conditions.

This definitely fits the bill.

**Comment by shubham-antier** [comment]
Removed the ETH receiving functionality from the contract

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Lithium-Ventures/zap-contracts-labs/pull/2

**Comment by Evert0x** [comment]
Planning to reject escalation. It's a recommendation to opt-in to bear yield. It's not an issue that will make the protocol or it's users lose funds

**Comment by Coareal** [comment]
Why is the inability to opt in to bear yield not a loss of fund for the protocol? Any funds stored in the contract cannot accrue yield for perpetuity.

**Comment by Evert0x** [comment]
Because there is no error in the implementation. The code works perfectly fine as is. That's why it's a recommendation/design choice.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Coareal](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/44/#issuecomment-2025913111): rejected

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
