### ISSUE TITLE
enfrasico - Wrong token address used for USDC

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zap-protocol-judging#47]
enfrasico

medium

# Wrong token address used for USDC

## Summary
Blast's USDB contract is at the precompile `0x4300000000000000000000000000000000000003`. This address is fixed on Blast mainnet.

## Vulnerability Detail
Protocol is however setting USDC address to `0xA9F81589Cc48Ff000166Bf03B3804A0d8Cec8114`. This is the wrong address and hence protocol is using the wrong USDB token.

## Impact
Usage of wrong USDB address.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/TokenSale.sol#L88

https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-launches-contracts/contracts/Admin.sol#L63

## Tool used

Manual Review

## Recommendation
Use the correct USDB address on Blast mainnet.

**Comment by Coareal** [comment]
Escalate

This issue is a valid medium. The use of a wrong USDB address renders the contract entirely useless. The ease of fixing this issue should not be used as a reason to make this issue invalid.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue is a valid medium. The use of a wrong USDB address renders the contract entirely useless. The ease of fixing this issue should not be used as a reason to make this issue invalid.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ZdravkoHr** [comment]
@Coareal, how does it render the contract useless? The USDB is not even used

**Comment by Coareal** [comment]
Hi @ZdravkoHr 

There is no USDC on Blast. USDC is automatically converted to USDB in the L1 -> L2 bridge. The correct contract should be the USDB precompile if we are interacting with USDC.

**Comment by ZdravkoHr** [comment]
That's a good point, @Coareal. But still the `USDB` variable is just declared, it's not used. So it being wrong wouldn't break any functionality, would it?

**Comment by Coareal** [comment]
Hi @ZdravkoHr 

The incorrect address is found in both `Admin.sol` and `TokenSale.sol`. USDB variable is not used in `Admin.sol`, but is used throughout the contract in `TokenSale.sol` under the variable `usdc`.

**Comment by ZdravkoHr** [comment]
Oh, I see what you mean now. I guess they left it invalid because of the comment. Will see what the final decision is

**Comment by ghost** [comment]
Responded in #62

**Comment by Evert0x** [comment]
Will reject escalation and keep issue state as is as it's clear based on the codebase that this address is a placeholder

> usdc = IERC20D(0xA9F81589Cc48Ff000166Bf03B3804A0d8Cec8114); //TODO change for mainnet

**Comment by Evert0x** [comment]
Result:
Invalid 
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Coareal](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/47/#issuecomment-2025921210): rejected
