### ISSUE TITLE
bughuntoor - Changing vesting points after vesting has started will lead to unexpected results

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zap-protocol-judging#52]
bughuntoor

high

# Changing vesting points after vesting has started will lead to unexpected results

## Summary
Changing vesting points after vesting has started will lead to unexpected results 

## Vulnerability Detail
Within the contract, there's a `updateVestingPoints`  function which allows change of the Vesting Points. 
```solidity
    function updateVestingPoints(
        uint128[2][] memory _vestingPoints
    ) external onlyRole(DEFAULT_ADMIN_ROLE) {
        uint256 sum;
        (vestingPoints, sum) = ascendingSort(_vestingPoints);
        require(sum == 10000, "sum not 10000");
        require(block.timestamp <= _vestingPoints[0][0], "Time lapsed");
    }
```
There's a require check at the end which makes sure that the the new vesting points will not have started. However, this isn't sufficient, as there would be problems if the vesting has already started (with the old vesting points).

Imagine the following scenario: 
1. There's 10 total vesting points, each of them giving 10% of the total vesting amount
2. Half of the vesting has gone by. A user has claimed for the first 5 points, claiming 50% of their vesting. Their index is 5. 
3. Vesting points are changed to new values. Now there are now only 2 vesting points.
4.  Since the user's index is higher than the total  number of vesting points, user cannot claim any more tokens.

In the end, the user has lost 50% of their vesting amount. 

Note: the change of vesting points can lead to both overdistributing funds and loss of funds.

## Impact
Loss of funds 

## Code Snippet
https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/Vesting.sol#L94C1-L101C6

## Tool used

Manual Review

## Recommendation
Add the following check in the beginning of the function 
```solidity
        require(block.timestamp <= vestingPoints[0][0], "Time lapsed");
```

**Comment by ZdravkoHr** [comment]
Escalate 

The vesting points being updated with faulty values after the vesting has started is an admin error.

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> The vesting points being updated with faulty values after the vesting has started is an admin error.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by detectiveking123** [comment]
This issue is invalid as the escalation says. Any issues would be a result of admin error.

**Comment by koreanspicygarlic1** [comment]
The changed values are not faulty - they are correct by all means. Not an admin input mistake, but rather a contract logic mistake

**Comment by detectiveking123** [comment]
How is it a contract logic mistake? The admin should not be adjusting past points anyways, and they can always craft the input correctly to update future points. 

It's also clear from the code that the admin shouldn't be making these updates after the start of vesting.

**Comment by armormadeofwoe** [comment]
> How is it a contract logic mistake? The admin should not be adjusting past points anyways, and they can always craft the input correctly to update future points.
> 
> It's also clear from the code that the admin shouldn't be making these updates after the start of vesting.

"They can always craft the input correctly" is a wild and delusional take. The protocol is expected to have several vesting points and users could claim at either one of them and store their corresponding index. It is not virtually possible to "correctly craft and update future points" when all users would have different indexes based on when they called `claim`. 

If it's "clear from the code" that admin should not be doing action X, then forbidding him from doing so would eliminate the possibility of ever happening.

The suggested mitigation really puts the -less in "trustless" which is what we are allegedly after in this field of work.

**Comment by detectiveking123** [comment]
Not sure how to respond to your comment, because it makes very little sense and is rooted in poor understanding of the code.

**Comment by ghost** [comment]
The argument posits a scenario where post-fundraising, IDO or presale teams possess the autonomy to modify tokenomics and vesting schedules at their discretion, suggesting a security vulnerability or a potential for misuse. Labeling this as an "admin error" minimizes its impact and potentially overlooks the broader implications of unchecked administrative powers. 
The ability for administrative roles to alter critical financial parameters post-fundraising without stringent checks or community consensus mechanisms reflects a design flaw or oversight in the smart contract's governance model.
Let me know if I am getting anything wrong here @detectiveking123 @deadrosesxyz

**Comment by detectiveking123** [comment]
"The ability for administrative roles to alter critical financial parameters post-fundraising without stringent checks or community consensus mechanisms reflects a design flaw or oversight in the smart contract's governance model."

Respectfully, these types of issues are not in scope of Sherlock when the admin is trusted.

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Lithium-Ventures/zap-contracts-labs/pull/4

**Comment by shubham-antier** [comment]
The function has been completely removed. The scope of adding vesting points has been limited to the initialize function.

**Comment by Evert0x** [comment]
Planning to accept escalation and invalidate issue.

This behavior is expected and is misuse of a trusted admin function.

**Comment by Evert0x** [comment]
Result:
Invalid 
Has Duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ZdravkoHr](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/52/#issuecomment-2025453360): accepted

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
