### ISSUE TITLE
bughuntoor - User will get wrong amount of tax refunded, if their tax rate changes

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zap-protocol-judging#56]
bughuntoor

high

# User will get wrong amount of tax refunded, if their tax rate changes

## Summary
User will get wrong amount of tax refunded, if their tax rate changes

## Vulnerability Detail
Upon every deposit in TokenSale, every user has to pay a certain amount of tax, based on their tax rate. 
```solidity
       if (sum > taxFreeAllcOfUser) {
            uint256 userTxRate = userTaxRate(sum, _sender);
            if (s.amount < taxFreeAllcOfUser) {
                userTaxAmount =
                    ((sum - taxFreeAllcOfUser) * userTxRate) /
                    POINT_BASE;
            } else {
                userTaxAmount = (amount * userTxRate) / POINT_BASE;
            }
        }

        if (userTaxAmount > 0) {
            s.taxAmount += userTaxAmount;
            usdc.safeTransferFrom(_sender, marketingWallet, userTaxAmount);
        }
```
After the private period finishes, users can get a tax refund. The problem is that if the user has used part of their non-tax-free allocation, their current tax rate is used to calculate the refund, and not their old one.

```solidity
        if (s.taxAmount > 0) {
            uint256 tax = userTaxRate(s.amount, msg.sender);
            uint256 taxFreeAllc = _maxTaxfreeAllocation(msg.sender) * PCT_BASE;
            if (taxFreeAllc >= s.share) {
                refundTaxAmount = s.taxAmount;
            } else {
                refundTaxAmount = (left * tax) / POINT_BASE; 
            }
            usdc.safeTransferFrom(marketingWallet, msg.sender, refundTaxAmount);
        }
```

Imagine the following scenario: 
1. Global tax rate is 1%
2. User makes 1000 USDC deposit, meaning that they pay 10 USDC in tax
3. Global tax rate is changed to 10% 
4. User has 500 USDC as max taxfree allocation, meaning that he must get a refund on the tax of these 500 USDC
5. When calculating the 500 tax refund, it will based on the new 10% tax rate. The user will be refunded 50 USDC, even though initially he paid only 10 USDC in tax 

## Impact
Loss of funds.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/TokenSale.sol#L381

## Tool used

Manual Review

## Recommendation
correctly calculate the tax refund

**Comment by spacegliderrrr** [comment]
Escalate

Tax rate is not constant. One, it can be changed from `setAllocationAndTax` and also the user's tax rate can change from getting un/whitelisted.

Believe it should be a valid high

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Tax rate is not constant. One, it can be changed from `setAllocationAndTax` and also the user's tax rate can change from getting un/whitelisted.
> 
> Believe it should be a valid high 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
Well for this I am waiting for sponsors to respond for having better clarity.

**Comment by ghost** [comment]
@niketansainiantier can you comment on this issue??

**Comment by Evert0x** [comment]
I believe it's clear that the taxrate can be updated and it can lead to a loss of funds as described.

**Comment by Evert0x** [comment]
Planning to accept escalation and upgrade to high

**Comment by detectiveking123** [comment]
@Evert0x This is definitely not a high

It's very unclear to me that the admins intend to update the tax rate throughout the TokenSale process and not just initially before sale start. There is a conditional loss of funds in the event that the admin makes these "incorrect" types of updates, which should be classified as admin error. This is at most a medium issue, possibly invalid. 

You can't see this as an unconditional loss of user funds, as the admin has to take a possibly incorrect action in order for it to occur. You could possibly see it as a breakage of core protocol functionality if you believe that the admin being able to update the tax rate after token sale start is core functionality.

**Comment by detectiveking123** [comment]
@Evert0x Actually, this issue is just completely invalid, see the following function which is meant to change the tax rate:

```
    function setAllocationAndTax(uint256[3] calldata _allocations) external {
        require(block.timestamp <= params.privateStart, "Time lapsed");
        require(admin.hasRole(OPERATOR, msg.sender), "TokenSale: OnlyOperator");
        maxAllocation = _allocations[0];
        globalTaxRate = _allocations[1];
        whitelistTxRate = _allocations[2];
    }
```

This can only be called before the TokenSale starts, which means this issue is irrelevant and can never lead to a loss of funds, as tax rate cannot be changed in the middle of token sale.

**Comment by deadrosesxyz** [comment]
@detectiveking123 
User's tax rate changes also based on being whitelisted or not which can be changed [here ](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/TokenSale.sol#L111) during the TokenSale
```solidity
    function whitelistUser(address[] calldata users) public {
        require(admin.hasRole(OPERATOR, msg.sender), "TokenSale: OnlyOperator");
        for (uint256 i = 0; i < users.length; i++) {
            isWhitelisted[users[i]] = true;
        }
    }
```

**Comment by detectiveking123** [comment]
I think it is pretty clear from the code that the admins are aware that the design of their system supports a static tax rate for each user. Whitelisting a user is an admin decision, and it is a design decision to either only whitelist before the sale or not be able to whitelist users who have already interacted with the token sale. Certainly, there is no core functionality being broken here. 

Given the ambiguity in the how the admin will interact with this function, it is correct to trust them to handle it correctly. Therefore, I still believe this issue to be a low.

**Comment by ghost** [comment]
@deadrosesxyz I agree with the points @detectiveking123 has made here, and it is indeed low if take into consideration that admin is going to change the tax rate during a tokensale

**Comment by merc1995** [comment]
>  Whitelisting a user is an admin decision, and it is a design decision to either only whitelist before the sale or not be able to whitelist users who have already interacted with the token sale. 
Do any docs mention this?

**Comment by detectiveking123** [comment]
@merc1995 The burden of proof is on you, not me. You need to find documentation proving that what I proposed is not a valid design decision. Otherwise, I could hypothetically take random parts of the codebase, tell you that they're designed incorrectly, and then ask you to find documentation proving that my interpretation is incorrect.

**Comment by merc1995** [comment]
So let the sponsor decide the right behavior, not us, thank you.

**Comment by Czar102** [comment]
From the docs:
> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

I believe this to be a low severity issue.

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [spacegliderrrr](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/56/#issuecomment-2024868008): rejected
