### ISSUE TITLE
bughuntoor - USDB hardcoded to wrong address

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zap-protocol-judging#62]
bughuntoor

high

# USDB hardcoded to wrong address

## Summary
Contract will be unusable as USDB is hardcoded to the wrong address 

## Vulnerability Detail
The initialize function has a wrong hardcoded address set for the USDB token address. 
The one in the function used is `0xA9F81589Cc48Ff000166Bf03B3804A0d8Cec8114`
The correct address on Blast is `0x4300000000000000000000000000000000000003`
```solidity
    function initialize(
        Params calldata _params,
        address _stakingContract,
        address _admin,
        uint256 _maxAllocation,
        uint256 _globalTaxRate,
        bool _isKYC,
        uint256 _whitelistTxRate
    ) external initializer {
        params = _params;
        stakingContract = IStaking(_stakingContract);
        admin = IAdmin(_admin);
        state.totalSupplyInValue = uint128(
            (uint256(_params.totalSupply) *
                uint256(_params.privateTokenPrice)) / 10 ** 18
            // removes USDB hardcode of six, awful
        );
        usdc = IERC20D(0xA9F81589Cc48Ff000166Bf03B3804A0d8Cec8114); //TODO change for mainnet
        marketingWallet = 0x6507fFd283c32386B6065EA89744Ade21515e91E; //TODO change for mainnet
        maxAllocation = _maxAllocation;
        globalTaxRate = _globalTaxRate;
        isKYCEnabled = _isKYC;
        whitelistTxRate = _whitelistTxRate;
    }
```
This will make the contact unusable 

## Impact
Contract unusable 

## Code Snippet
https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/TokenSale.sol#L88

## Tool used

Manual Review

## Recommendation
change the address to the correct one 

Duplicate of #26

**Comment by spacegliderrrr** [comment]
Escalate 

this should be a valid issue. Once the usdb address is set in the initializer, it cannot be changed. It renders the whole contract useless.

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> this should be a valid issue. Once the usdb address is set in the initializer, it cannot be changed. It renders the whole contract useless. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by detectiveking123** [comment]
@spacegliderrrr Please read the comment on that line

**Comment by ghost** [comment]
Was mentioned in comments of codebase that USDB address should be changed, Even if overlook that then this issue is borderline low/medium, I will let @Czar102 decide this one.

**Comment by Evert0x** [comment]
@Hash01011122 can you link to those comments in the codebase?

**Comment by detectiveking123** [comment]
@Evert0x There's a comment on that line in the code snippet in the issue

`usdc = IERC20D(0xA9F81589Cc48Ff000166Bf03B3804A0d8Cec8114); //TODO change for mainnet`

**Comment by ghost** [comment]
As I mentioned earlier to me, it's invalid, as it's clearly written in the codebase TO DO comment to change the address. Even if reconsider and accept it as an issue, it's hardly low or informational issue

**Comment by Evert0x** [comment]
Agree. Will reject escalation and keep issue state as is

**Comment by Evert0x** [comment]
Result:
Invalid 
Duplicate of #26

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [spacegliderrrr](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/62/#issuecomment-2024872569): rejected
