### ISSUE TITLE
cats - Updating vesting points overwrites them instead of updating them

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zap-protocol-judging#65]
cats

medium

# Updating vesting points overwrites them instead of updating them

## Summary
The function to update vesting points in the vesting contract overwrites them instead of updating them.
## Vulnerability Detail
If we take a closer look at the `updateVestingPoints()` function we can see that instead of updating them, we are just [overwriting them](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/c2ad35aa844899fa24f6ed0cbfcf6c7e611b061a/zap-contracts-labs/contracts/Vesting.sol#L98).

```solidity
    (vestingPoints, sum) = ascendingSort(_vestingPoints);
```

Overwriting the existing ones could mess up the whole process of users redeeming points in case they have not redeemed previous ones or if they have redeemed to a certain point (example 3rd) and then new ones are added. Since all vesting points must sum up to 100%:

1. Original points schedule is 10%, 20%, 20%, 25%, 25%
2. Alice claims up to 3rd, so 50% of her vesting
3. Vesting points are updated to 15%, 15%, 35%, 35%
4. Alice later claims new 4th and 5th, her total vesting claimed is now 120% instead of 100%
## Impact
If users have/haven't claimed previous vesting points and the admins overwrite them it could mess up the whole process.
## Code Snippet
```solidity
    (vestingPoints, sum) = ascendingSort(_vestingPoints);
```
## Tool used
Manual Review
## Recommendation
Update instead of overwrite.

Duplicate of #52

**Comment by 0xcats** [comment]
Escalate
I don't quite understand why this is excluded. It is a duplicate of #52. I have provided clear and concise points as well as an example scenario how this can lead to both over-distribution or loss of funds.

**Comment by ghost** [comment]
This is valid duplicate of #52

**Comment by Evert0x** [comment]
Agree it's the same core issue, planning to accept and duplicate. But the issue might get invalidated as it's an admin (trusted) function

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #52

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xcats](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/65/#issuecomment-2024632665): accepted
