### ISSUE TITLE
ZdravkoHr. - `USDC.safeTransferFrom` uses wrong decimal precisions in `TokenSale.sol`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zap-protocol-judging#73]
ZdravkoHr.

high

# `USDC.safeTransferFrom` uses wrong decimal precisions in `TokenSale.sol`

## Summary
USDC has 6 decimals, but [`TokenSale.sol`](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/c2ad35aa844899fa24f6ed0cbfcf6c7e611b061a/zap-contracts-labs/contracts/TokenSale.sol) makes transfers with mixed decimals. 

## Vulnerability Detail
There are several places in the contract where USDC transfers are initiated. However, the amount passed to `safeTransferFrom` in some of them has wrong decimal precision.

This will make the contract behave in unexpected ways. For example, in [`_processPrivate`](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/c2ad35aa844899fa24f6ed0cbfcf6c7e611b061a/zap-contracts-labs/contracts/TokenSale.sol#L217-L253), the amount's precision is very high for both transfers. As a result, most deposits will fail because users will not have this much tokens. It's even worse if they have because the contract may take all of them. 

```solidity
     * @param _amount - investment amount in usdc
    function _processPrivate(address _sender, uint256 _amount) internal {
        uint256 amount = _amount * PCT_BASE;
        userTaxAmount = (amount * userTxRate) / POINT_BASE;
     
        usdc.safeTransferFrom(_sender, marketingWallet, userTaxAmount);
        usdc.safeTransferFrom(_sender, address(this), amount);
    }
```

In [`takeUSDCRaised`](https://github.com/sherlock-audit/2024-03-zap-protocol/blob/c2ad35aa844899fa24f6ed0cbfcf6c7e611b061a/zap-contracts-labs/contracts/TokenSale.sol#L337C1-L359C6), `earned` is meant to be a variable with 18 decimals. It is compared with `bal` which has only 6 decimals. This will sweep the whole contract's balance.

```solidity
    function takeUSDCRaised() external override {
        checkingEpoch();
        require(epoch == Epoch.Finished, "TokenSale: Not time yet");
        require(!isRaiseClaimed, "TokenSale: Already paid");

        uint256 earned;

        if (state.totalPrivateSold > state.totalSupplyInValue) {
            earned = uint256(state.totalSupplyInValue);
        } else {
            earned = uint256(state.totalPrivateSold);
        }

        isRaiseClaimed = true;

        if (earned > 0) {
            uint256 bal = usdc.balanceOf(address(this));
            uint256 returnValue = earned <= bal ? earned : bal;
            usdc.safeTransfer(admin.wallet(), returnValue);
        }

        emit RaiseClaimed(admin.wallet(), earned);
    }
```

And in `claim`[https://github.com/sherlock-audit/2024-03-zap-protocol/blob/c2ad35aa844899fa24f6ed0cbfcf6c7e611b061a/zap-contracts-labs/contracts/TokenSale.sol#L364-L392], the same problems exists as in `_processPrivate`

## Impact
Broken core functionality, can lead to loss of funds and unexpected transfers and states in some cases.

## Code Snippet
Provided above.

## Tool used

Manual Review

## Recommendation
Each of the transfers should use variables with 6 decimals precision as amount.

Duplicate of #87

**Comment by ZdravkoHr** [comment]
Escalate 
I believe this issue should be a separate one from #87. The root cause in #87 is the wrong use of `PCT_AMOUT` while this issue shows that usdc transfers across the whole contract are broken.

**Comment by sherlock-admin2** [comment]
> Escalate 
> I believe this issue should be a separate one from #87. The root cause in #87 is the wrong use of `PCT_AMOUT` while this issue shows that usdc transfers across the whole contract are broken.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
In blast USDC has 18 decimals.
[Blast USDC](https://blastexplorer.io/token/0x870a8F46b62B8BDeda4c02530C1750CddF2ED32e)

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue state as is

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #87

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ZdravkoHr](https://github.com/sherlock-audit/2024-03-zap-protocol-judging/issues/73/#issuecomment-2025542227): rejected
