### ISSUE TITLE
ydlee - Incorrect amount of USDCs are transfered when depositing to `TokenSale`.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zap-protocol-judging#94]
ydlee

high

# Incorrect amount of USDCs are transfered when depositing to `TokenSale`.

## Summary
When depositing to `TokenSale`, the amount of USDC transferred is incorrect, and PCT_BASE (10**18) is used as the unit of USDC. However, the decimals of USDC is 6, so the amount of USDC transferred is incorrect. This can lead to incorrect token amounts being transferred.

## Vulnerability Detail
Function `deposit` calls function `_processPrivate` to update state and staked data, and transfer USDC tokens. At line 221, the inputed amount of USDC `_amount` is converted to `amount` in `PCT_BASE` (10**18). Then the tax is calculated by `amount` and thus in `PCT_BASE` too (line 238). Finally, tax and `amount` of USDCs are transferred, both in `PCT_BASE` (line 244 and 248). It is wrong, as USDC has 6 decimals, and the amount of USDC transferred is incorrect.
```solidity
217:    function _processPrivate(address _sender, uint256 _amount) internal {
...
220:        Staked storage s = stakes[_sender];
221:@>      uint256 amount = _amount * PCT_BASE;
222:        uint256 sum = s.amount + amount;
...
227:        uint256 taxFreeAllcOfUser = 0; // hardcode zero - all pools have ax
228:
229:        uint256 userTaxAmount;
230:
231:        if (sum > taxFreeAllcOfUser) {
232:            uint256 userTxRate = userTaxRate(sum, _sender);
233:            if (s.amount < taxFreeAllcOfUser) {
234:                userTaxAmount =
235:                    ((sum - taxFreeAllcOfUser) * userTxRate) / 
236:                    POINT_BASE;
237:            } else {
238:@>              userTaxAmout = (amount * userTxRate) / POINT_BASE;
239:            }
240:        }
241:
242:        if (userTaxAmount > 0) {
243:            s.taxAmount += userTaxAmount;
244:@>          usdc.safeTransferFrom(_sender, marketingWallet, userTaxAmount);
245:        }
246:        s.amount += uint128(amount);
247:        state.totalPrivateSold += uint128(amount);
248:@>      usdc.safeTransferFrom(_sender, address(this), amount);
...
253:    }
```
https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/TokenSale.sol#L217-L253

## Impact
Incorrect amount of USDCs are transferred when depositing.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zap-protocol/blob/main/zap-contracts-labs/contracts/TokenSale.sol#L217-L253

## Tool used

Manual Review

## Recommendation
When transferring USDCs, calculate the amount with correct decimals.
```solidity
242:        if (userTaxAmount > 0) {
243:            s.taxAmount += userTaxAmount;
244:-            usdc.safeTransferFrom(_sender, marketingWallet, userTaxAmount);
244:+            usdc.safeTransferFrom(_sender, marketingWallet, userTaxAmount / PCT_BASE);
245:        }
246:        s.amount += uint128(amount);
247:        state.totalPrivateSold += uint128(amount);
248:-        usdc.safeTransferFrom(_sender, address(this), amount);
248:+        usdc.safeTransferFrom(_sender, address(this), _amount);
```

Duplicate of #87

**Comment by ghost** [comment]
Duplicate of #51
